Feature/rewrite order view
paysuper/paysuper-billing-server pull request #497
Opened 2020-10-22 19:52 UTC by shersh

2020-10-23 09:44 UTC, EvgeniyStrigo requested changes
Ну и самое главное - тесты массово падают

2020-10-23 09:44 UTC, EvgeniyStrigo commented on internal/helper/money.go
> +func (m *Money) RoundOrDefault(val float64) float64 {
Я вижу тут какое-то внутреннее противоречие )

Если функция называется RoundOrDefault, то у нее должно быть два аргумента - val и defaultVal
А если исходить из того как написано тело функции, то она должна называться RoundOrZero :-)

2020-10-23 09:44 UTC, EvgeniyStrigo commented on internal/repository/order.go
> +		query := bson.M{"order_id": oid}
Рома, ты уверен что так? У тебя же на входе должен быть массив id ордеров, и чтобы по нему найти проводки, нужно в запросе искать по source.id а не по order_id

2020-10-23 09:44 UTC, EvgeniyStrigo commented on internal/repository/order.go
> +		cursor, err := h.db.Collection(collectionAccountingEntry).Find(ctx, query)
Тут мы лезем напрямую в коллекцию, а не через репозиторий internal/repository/accounting_entry.go, почему? Типа чтобы репозитории не зависели друг от друга?

2020-10-23 09:57 UTC, shersh commented on internal/repository/order.go
> +		cursor, err := h.db.Collection(collectionAccountingEntry).Find(ctx, query)
Ну да, у нас нету зависимости сейчас у order_view репы от accounting репы.

2020-10-23 09:58 UTC, shersh commented on internal/helper/money.go
> +func (m *Money) RoundOrDefault(val float64) float64 {
Согласен) Этот метод правда так и не понадобился, поэтому удалю его от греха

2020-10-23 09:58 UTC, shersh commented on internal/repository/order.go
> +		query := bson.M{"order_id": oid}
Перепроверю еще раз. Но массив там точно не должен быть же

2020-10-23 10:13 UTC, EvgeniyStrigo commented on internal/repository/order.go
> +		query := bson.M{"order_id": oid}
Я тут не про массив, а про то что имхо должно быть 
не
query := bson.M{"order_id": oid}
а
query := bson.M{"source.id": oid}

2020-10-27 17:27 UTC, EvgeniyStrigo approved these changes

2020-10-27 17:28 UTC, merged