Add sending email to admin after merchant document uploaded
paysuper/paysuper-billing-server pull request #522
Opened 2020-11-09 06:38 UTC by shersh

2020-11-09 09:44 UTC, pr0head requested changes

2020-11-09 09:44 UTC, pr0head commented on internal/config/config.go
> +	EmailAdminDocumentViewer string `envconfig:"EMAIL_ADMIN_DOCUMENT_VIEWER" default:"anton.krainiuk@pay.super.com"`
В проекте есть параметр конфигурации `EMAIL_ONBOARDING_ADMIN_RECIPIENT`, его нельзя использовать?

2020-11-09 09:44 UTC, pr0head commented on internal/service/merchant_document.go
> +				"file_path":   req.FilePath,
Не, FilePath тут точно не нужен. Это путь файла на S3, пользователям он точно не нужен.

2020-11-09 09:44 UTC, pr0head commented on internal/service/merchant_document.go
> +			TemplateModel: map[string]string{
Подозрительно что данных для админа нет совсем. Это не ошибка?

2020-11-09 09:44 UTC, pr0head commented on internal/service/merchant_document.go
> +	err = s.postmarkBroker.Publish(postmarkpb.PostmarkSenderTopicName, payload, amqp.Table{})
Возможно ошибочно предполагаю, что в письме должна быть ссылка на просмотр документа или листинга документов. Если это так, то ссылку нужно генерить на бэке, чтобы упростить тестирование (не зашивать домен в письме)

2020-11-09 09:49 UTC, pr0head commented
И еще не хватает тестов, проверить что при добавлении документа админом или мерчем мы вызвали сервис постмарка для отправки письма.

2020-11-10 07:59 UTC, shersh commented on internal/config/config.go
> +	EmailAdminDocumentViewer string `envconfig:"EMAIL_ADMIN_DOCUMENT_VIEWER" default:"anton.krainiuk@pay.super.com"`
Не уверен, лучше использовать разные ИМХО

2020-11-10 07:59 UTC, shersh commented on internal/service/merchant_document.go
> +				"file_path":   req.FilePath,
Это не пользователю, а админу же!

2020-11-10 07:59 UTC, shersh commented on internal/service/merchant_document.go
> +			TemplateModel: map[string]string{
А это как раз для пользователя

2020-11-10 08:00 UTC, shersh commented on internal/service/merchant_document.go
> +	err = s.postmarkBroker.Publish(postmarkpb.PostmarkSenderTopicName, payload, amqp.Table{})
Я же ссылку для документа кладу в "file_path":   req.FilePath )

2020-11-10 08:24 UTC, pr0head commented on internal/config/config.go
> +	EmailAdminDocumentViewer string `envconfig:"EMAIL_ADMIN_DOCUMENT_VIEWER" default:"anton.krainiuk@pay.super.com"`
Это же тоже кейс онбординга, мне кажется логично что общая почта будет. @EvgeniyStrigo что думаешь?

2020-11-10 08:27 UTC, pr0head commented on internal/service/merchant_document.go
> +				"file_path":   req.FilePath,
Мы не можем отдавать файл напрямую с С3, только через хэндлер на мапи, так как нужно проверить права пользователя. Поэтому в письме данный путь будет бесплезен. Там нужен путь на страницу мерча/админа с просмотром файла или сразу на хэндлер скачивания

2020-11-10 08:27 UTC, pr0head commented on internal/service/merchant_document.go
> +	err = s.postmarkBroker.Publish(postmarkpb.PostmarkSenderTopicName, payload, amqp.Table{})
Выше ответил про этот путь

2020-11-10 13:18 UTC, EvgeniyStrigo commented on internal/config/config.go
> +	EmailAdminDocumentViewer string `envconfig:"EMAIL_ADMIN_DOCUMENT_VIEWER" default:"anton.krainiuk@pay.super.com"`
Это должна быть одна и та же почта, конечно же.

2020-11-11 10:32 UTC, merged