Feature/recurring subscription
paysuper/paysuper-billing-server pull request #563
Opened 2021-02-10 16:46 UTC by pr0head

2021-02-10 16:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/paysuper/paysuper-billing-server?pullRequest=563) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/paysuper/paysuper-billing-server?pullRequest=563) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: pr0head<br/>:x: vesvalo<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/paysuper/paysuper-billing-server?pullRequest=563) it.</sub>

2021-02-11 09:41 UTC, EvgeniyStrigo requested changes

2021-02-11 09:41 UTC, EvgeniyStrigo commented on internal/mocks/compile.cmd
> -mockery --recursive=true --name=BillingService --dir=../../pkg/proto/grpc --output=../../pkg/mocks
А чего генерацию моков тут убрал? Типа, они в прото-репе генерятся?

2021-02-11 09:41 UTC, EvgeniyStrigo commented on internal/repository/models/recurring_subscription.go
> +	LastPaymentAt         time.Time             `bson:"last_payment_at"`
А значение у LastPaymentAt есть всегда? Или могут быть ситуации когда оно пустое? 
Я к тому, что не должно ли тут time.Time быть ссылкой, как в DeletedAt выше?

2021-02-11 09:41 UTC, EvgeniyStrigo commented on internal/service/refund.go
> +		subscription.TotalAmount -= subscription.Plan.Charge.Amount
Вот тут не может ли появится расхождения между планом и фактом? 
Сумма рефанда всегда будет строго равна сумме подписки?
Сумма подписки со временем никогда не меняется?

2021-02-11 09:41 UTC, EvgeniyStrigo commented on internal/service/service.go
> +	s.recurringPlanRepository = repository.NewRecurringPlanRepository(s.db)
А второй строки, про recurringSubscriptionRepository тут не должно быть?

2021-02-11 09:41 UTC, EvgeniyStrigo commented on internal/service/webhook.go
> -	case pkg.OrderTypeVirtualCurrency:
А куда делся кусок про виртуальные валюты?

2021-02-11 09:41 UTC, EvgeniyStrigo commented on internal/service/token.go
> -	case pkg.OrderTypeVirtualCurrency:
А куда делся кусок про виртуалные валюты?

2021-02-11 09:41 UTC, EvgeniyStrigo commented on migrations/20210209145300_create_recurring_subscription_collection.up.json
> +        "unique": true
А в чем смысл того. что индекс уникален? expire_at это же время, можно создать кастомеру две подписки на один и тот же план с разницей в 1 секунду (или даже меньше - какая там точность у поля?) и они будут "уникальными" )

2021-02-11 09:44 UTC, pr0head commented on internal/service/refund.go
> +		subscription.TotalAmount -= subscription.Plan.Charge.Amount
У нас рефанд можно сделать только на всю сумму, так что по идее не должно быть расхождений
Сумма подписки не меняется. Собственно мы внутри подписки храним слепок плана на момент его создания.
Если мерчант поменяет стоимость подписки, то это отразится только на новых подписках, старые структуры не изменятся.

2021-02-11 09:45 UTC, pr0head commented on internal/service/webhook.go
> -	case pkg.OrderTypeVirtualCurrency:
Это старые артефакты. Мы с Мишей разбирали эти кейсы и выяснили, что виртуальные валюты у нас продаются только как продукт. У нас нет и не может быть сейчас ордеров с типом "вирт.валюта"

2021-02-11 09:45 UTC, pr0head commented on internal/service/token.go
> -	case pkg.OrderTypeVirtualCurrency:
Ответ выше

2021-02-11 09:48 UTC, pr0head commented on internal/mocks/compile.cmd
> -mockery --recursive=true --name=BillingService --dir=../../pkg/proto/grpc --output=../../pkg/mocks
Верно

2021-02-11 09:56 UTC, pr0head commented on internal/repository/models/recurring_subscription.go
> +	LastPaymentAt         time.Time             `bson:"last_payment_at"`
Он может быть пустым только если мы создадим подписку, но по какой-то причине не проведем вебхук от КП об оплате рекарринг подписки. В этом случае у нас будет отрицательное значение. Сейчас поправлю на ссылку, согласен пусть лучше null будет если что-то пойдет не так.

2021-02-11 14:06 UTC, pr0head commented on internal/repository/models/recurring_subscription.go
> +	LastPaymentAt         time.Time             `bson:"last_payment_at"`
Fixed

2021-02-11 14:06 UTC, pr0head commented on internal/service/service.go
> +	s.recurringPlanRepository = repository.NewRecurringPlanRepository(s.db)
Fixed

2021-02-11 14:07 UTC, pr0head commented on migrations/20210209145300_create_recurring_subscription_collection.up.json
> +        "unique": true
И правда, получилось бессмысленно для этого кейса. Переделал индексы, сделал отдельную проверку на наличие активной подписки при создании.

2021-02-11 15:13 UTC, EvgeniyStrigo approved these changes

2021-02-17 11:22 UTC, EvgeniyStrigo commented on internal/service/recurring.go
> +		typ == billingpb.RecurringPeriodMinute && value > 60 ||
какое-то куцее название переменно - typ :)

2021-02-17 14:17 UTC, pr0head commented on internal/service/recurring.go
> +		typ == billingpb.RecurringPeriodMinute && value > 60 ||
Fixed)

2021-02-24 11:53 UTC, merged